import type {
  User,
  Team,
  Department,
  Objective,
  KeyResult,
  CompanyValue,
  CheckinQuestion,
} from './types'

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Sarah Chen',
    email: 'sarah.chen@company.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    jobTitle: 'CEO',
    role: 'admin',
  },
  {
    id: 'user-2',
    name: 'Michael Torres',
    email: 'michael.torres@company.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    jobTitle: 'VP of Engineering',
    departmentId: 'dept-1',
    managerId: 'user-1',
    role: 'manager',
  },
  {
    id: 'user-3',
    name: 'Emily Johnson',
    email: 'emily.johnson@company.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    jobTitle: 'Senior Engineer',
    departmentId: 'dept-1',
    teamId: 'team-1',
    managerId: 'user-2',
    role: 'employee',
  },
  {
    id: 'user-4',
    name: 'David Kim',
    email: 'david.kim@company.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    jobTitle: 'Product Manager',
    departmentId: 'dept-2',
    teamId: 'team-2',
    managerId: 'user-1',
    role: 'manager',
  },
  {
    id: 'user-5',
    name: 'Lisa Wang',
    email: 'lisa.wang@company.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    jobTitle: 'Designer',
    departmentId: 'dept-2',
    teamId: 'team-2',
    managerId: 'user-4',
    role: 'employee',
  },
]

// Mock Departments
export const mockDepartments: Department[] = [
  { id: 'dept-1', name: 'Engineering' },
  { id: 'dept-2', name: 'Product' },
  { id: 'dept-3', name: 'Sales' },
  { id: 'dept-4', name: 'Marketing' },
]

// Mock Teams
export const mockTeams: Team[] = [
  { id: 'team-1', name: 'Platform Team', departmentId: 'dept-1', description: 'Core platform infrastructure' },
  { id: 'team-2', name: 'Product Design', departmentId: 'dept-2', description: 'User experience and design' },
  { id: 'team-3', name: 'Growth', departmentId: 'dept-3', description: 'Sales and business development' },
]

// Mock Objectives
export const mockObjectives: Objective[] = [
  // Company Level
  {
    id: 'obj-1',
    title: 'Achieve $10M ARR by end of year',
    description: 'Scale the business to $10M in annual recurring revenue through product-led growth and enterprise sales.',
    level: 'company',
    ownerId: 'user-1',
    timePeriod: 'Q1 2026',
    progress: 42,
    confidenceLevel: 7,
    status: 'active',
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'obj-2',
    title: 'Build a world-class engineering team',
    description: 'Hire and retain top engineering talent to support rapid product development.',
    level: 'company',
    ownerId: 'user-1',
    timePeriod: 'Q1 2026',
    progress: 65,
    confidenceLevel: 8,
    status: 'active',
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-15'),
  },
  // Department Level
  {
    id: 'obj-3',
    title: 'Ship v2.0 platform with 99.9% uptime',
    description: 'Launch the next major version of our platform with enterprise-grade reliability.',
    level: 'department',
    parentId: 'obj-2',
    ownerId: 'user-2',
    departmentId: 'dept-1',
    timePeriod: 'Q1 2026',
    progress: 55,
    confidenceLevel: 6,
    status: 'active',
    createdAt: new Date('2026-01-02'),
    updatedAt: new Date('2026-01-15'),
  },
  // Team Level
  {
    id: 'obj-4',
    title: 'Reduce infrastructure costs by 30%',
    description: 'Optimize cloud spending while maintaining performance and reliability.',
    level: 'team',
    parentId: 'obj-3',
    ownerId: 'user-3',
    teamId: 'team-1',
    timePeriod: 'Q1 2026',
    progress: 70,
    confidenceLevel: 8,
    status: 'active',
    createdAt: new Date('2026-01-03'),
    updatedAt: new Date('2026-01-15'),
  },
  // Individual Level
  {
    id: 'obj-5',
    title: 'Complete Kubernetes migration',
    description: 'Migrate all services to Kubernetes for better scalability.',
    level: 'individual',
    parentId: 'obj-4',
    ownerId: 'user-3',
    timePeriod: 'Q1 2026',
    progress: 45,
    confidenceLevel: 5,
    status: 'active',
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-01-15'),
  },
]

// Mock Key Results
export const mockKeyResults: KeyResult[] = [
  // KRs for Company Objective 1 (Revenue)
  {
    id: 'kr-1',
    objectiveId: 'obj-1',
    ownerId: 'user-1',
    title: 'Increase MRR from $600K to $833K',
    metricType: 'currency',
    startValue: 600000,
    targetValue: 833000,
    currentValue: 720000,
    unit: '$',
    progress: 51,
    confidenceLevel: 7,
    status: 'on_track',
    weight: 1,
    sortOrder: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'kr-2',
    objectiveId: 'obj-1',
    ownerId: 'user-4',
    title: 'Close 5 enterprise deals worth $500K+ each',
    metricType: 'number',
    startValue: 0,
    targetValue: 5,
    currentValue: 2,
    unit: 'deals',
    progress: 40,
    confidenceLevel: 6,
    status: 'at_risk',
    weight: 1,
    sortOrder: 1,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'kr-3',
    objectiveId: 'obj-1',
    ownerId: 'user-1',
    title: 'Reduce customer churn to under 2%',
    metricType: 'percentage',
    startValue: 5,
    targetValue: 2,
    currentValue: 3.5,
    progress: 50,
    confidenceLevel: 7,
    status: 'on_track',
    weight: 1,
    sortOrder: 2,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-15'),
  },

  // KRs for Company Objective 2 (Team)
  {
    id: 'kr-4',
    objectiveId: 'obj-2',
    ownerId: 'user-2',
    title: 'Hire 10 senior engineers',
    metricType: 'number',
    startValue: 0,
    targetValue: 10,
    currentValue: 7,
    unit: 'engineers',
    progress: 70,
    confidenceLevel: 8,
    status: 'on_track',
    weight: 1,
    sortOrder: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'kr-5',
    objectiveId: 'obj-2',
    ownerId: 'user-2',
    title: 'Achieve employee NPS of 50+',
    metricType: 'number',
    startValue: 35,
    targetValue: 50,
    currentValue: 45,
    progress: 67,
    confidenceLevel: 8,
    status: 'on_track',
    weight: 1,
    sortOrder: 1,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-15'),
  },

  // KRs for Engineering Objective (Platform)
  {
    id: 'kr-6',
    objectiveId: 'obj-3',
    ownerId: 'user-2',
    title: 'Achieve 99.9% uptime',
    metricType: 'percentage',
    startValue: 99.5,
    targetValue: 99.9,
    currentValue: 99.7,
    progress: 50,
    confidenceLevel: 6,
    status: 'at_risk',
    weight: 1,
    sortOrder: 0,
    createdAt: new Date('2026-01-02'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'kr-7',
    objectiveId: 'obj-3',
    ownerId: 'user-3',
    title: 'Reduce P95 latency to under 200ms',
    metricType: 'number',
    startValue: 450,
    targetValue: 200,
    currentValue: 280,
    unit: 'ms',
    progress: 68,
    confidenceLevel: 7,
    status: 'on_track',
    weight: 1,
    sortOrder: 1,
    createdAt: new Date('2026-01-02'),
    updatedAt: new Date('2026-01-15'),
  },

  // KRs for Team Objective (Cost)
  {
    id: 'kr-8',
    objectiveId: 'obj-4',
    ownerId: 'user-3',
    title: 'Reduce AWS spending by $50K/month',
    metricType: 'currency',
    startValue: 0,
    targetValue: 50000,
    currentValue: 35000,
    unit: '$',
    progress: 70,
    confidenceLevel: 8,
    status: 'on_track',
    weight: 1,
    sortOrder: 0,
    createdAt: new Date('2026-01-03'),
    updatedAt: new Date('2026-01-15'),
  },

  // KRs for Individual Objective (K8s)
  {
    id: 'kr-9',
    objectiveId: 'obj-5',
    ownerId: 'user-3',
    title: 'Migrate all 12 services to Kubernetes',
    metricType: 'number',
    startValue: 0,
    targetValue: 12,
    currentValue: 5,
    unit: 'services',
    progress: 42,
    confidenceLevel: 5,
    status: 'at_risk',
    weight: 1,
    sortOrder: 0,
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'kr-10',
    objectiveId: 'obj-5',
    ownerId: 'user-3',
    title: 'Zero downtime during migration',
    metricType: 'binary',
    startValue: 0,
    targetValue: 1,
    currentValue: 1,
    progress: 100,
    confidenceLevel: 9,
    status: 'completed',
    weight: 0.5,
    sortOrder: 1,
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-01-15'),
  },
]

// Mock Company Values
export const mockCompanyValues: CompanyValue[] = [
  {
    id: 'value-1',
    name: 'Customer First',
    description: 'We put our customers at the center of everything we do',
    emoji: '🎯',
    color: '#FDB515',
    isActive: true,
    sortOrder: 0,
  },
  {
    id: 'value-2',
    name: 'Innovation',
    description: 'We push boundaries and embrace new ideas',
    emoji: '💡',
    color: '#22C55E',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'value-3',
    name: 'Teamwork',
    description: 'We achieve more together than alone',
    emoji: '🤝',
    color: '#3B82F6',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'value-4',
    name: 'Integrity',
    description: 'We do the right thing, even when no one is watching',
    emoji: '⭐',
    color: '#8B5CF6',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'value-5',
    name: 'Growth Mindset',
    description: 'We learn from failures and celebrate progress',
    emoji: '🌱',
    color: '#EC4899',
    isActive: true,
    sortOrder: 4,
  },
]

// Mock Check-in Questions
export const mockCheckinQuestions: CheckinQuestion[] = [
  {
    id: 'q-1',
    questionText: "What was your biggest accomplishment this week?",
    category: 'reflection',
    isActive: true,
  },
  {
    id: 'q-2',
    questionText: "What challenges did you face, and how did you overcome them?",
    category: 'blockers',
    isActive: true,
  },
  {
    id: 'q-3',
    questionText: "What are your top priorities for next week?",
    category: 'goals',
    isActive: true,
  },
  {
    id: 'q-4',
    questionText: "Is there anything your manager can help you with?",
    category: 'feedback',
    isActive: true,
  },
  {
    id: 'q-5',
    questionText: "How are you feeling about your work-life balance?",
    category: 'wellbeing',
    isActive: true,
  },
  {
    id: 'q-6',
    questionText: "What's one thing you learned this week?",
    category: 'reflection',
    isActive: true,
  },
  {
    id: 'q-7',
    questionText: "What blockers are slowing you down?",
    category: 'blockers',
    isActive: true,
  },
  {
    id: 'q-8',
    questionText: "How confident are you in achieving your OKRs this quarter?",
    category: 'goals',
    isActive: true,
  },
]

// ============================================
// NATALIE FLEMING - Director of People Ops
// Sample data for demo purposes
// ============================================

export const natalieUser: User = {
  id: 'user-natalie',
  name: 'Natalie Fleming',
  email: 'natalie.fleming@company.com',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Natalie',
  jobTitle: 'Director of People Ops',
  departmentId: 'dept-people',
  managerId: 'user-1',
  role: 'manager',
}

export const peopleOpsDepartment: Department = {
  id: 'dept-people',
  name: 'People Operations',
}

export const peopleOpsTeam: Team = {
  id: 'team-people',
  name: 'People & Culture',
  departmentId: 'dept-people',
  description: 'Employee experience and talent development',
}

// Direct reports for Natalie
export const natalieDirectReports: User[] = [
  {
    id: 'user-hr1',
    name: 'Marcus Chen',
    email: 'marcus.chen@company.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    jobTitle: 'HR Business Partner',
    departmentId: 'dept-people',
    teamId: 'team-people',
    managerId: 'user-natalie',
    role: 'employee',
  },
  {
    id: 'user-hr2',
    name: 'Sophie Anderson',
    email: 'sophie.anderson@company.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie',
    jobTitle: 'Talent Acquisition Specialist',
    departmentId: 'dept-people',
    teamId: 'team-people',
    managerId: 'user-natalie',
    role: 'employee',
  },
]

export const natalieObjectives: Objective[] = [
  {
    id: 'obj-nat-1',
    title: 'Improve employee engagement and retention',
    description: 'Create a workplace culture where employees thrive, feel valued, and want to stay long-term.',
    level: 'department',
    ownerId: 'user-natalie',
    departmentId: 'dept-people',
    timePeriod: 'Q1 2026',
    progress: 58,
    confidenceLevel: 7,
    status: 'active',
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'obj-nat-2',
    title: 'Build strong manager capabilities across the org',
    description: 'Equip all people managers with skills and tools to effectively lead and develop their teams.',
    level: 'department',
    parentId: 'obj-2', // Aligns with "Build world-class team"
    ownerId: 'user-natalie',
    departmentId: 'dept-people',
    timePeriod: 'Q1 2026',
    progress: 72,
    confidenceLevel: 8,
    status: 'active',
    createdAt: new Date('2026-01-02'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'obj-nat-3',
    title: 'Streamline hiring and onboarding processes',
    description: 'Create an efficient, candidate-friendly hiring process and world-class onboarding experience.',
    level: 'individual',
    parentId: 'obj-nat-2',
    ownerId: 'user-natalie',
    timePeriod: 'Q1 2026',
    progress: 45,
    confidenceLevel: 6,
    status: 'active',
    createdAt: new Date('2026-01-03'),
    updatedAt: new Date('2026-01-15'),
  },
]

export const natalieKeyResults: KeyResult[] = [
  // KRs for Engagement objective
  {
    id: 'kr-nat-1',
    objectiveId: 'obj-nat-1',
    ownerId: 'user-natalie',
    title: 'Increase employee NPS from 35 to 55',
    metricType: 'number',
    startValue: 35,
    targetValue: 55,
    currentValue: 47,
    progress: 60,
    confidenceLevel: 7,
    status: 'on_track',
    weight: 1,
    sortOrder: 0,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'kr-nat-2',
    objectiveId: 'obj-nat-1',
    ownerId: 'user-natalie',
    title: 'Reduce voluntary turnover from 18% to 10%',
    metricType: 'percentage',
    startValue: 18,
    targetValue: 10,
    currentValue: 14,
    progress: 50,
    confidenceLevel: 6,
    status: 'at_risk',
    weight: 1,
    sortOrder: 1,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'kr-nat-3',
    objectiveId: 'obj-nat-1',
    ownerId: 'user-hr1',
    title: 'Achieve 90% participation in quarterly engagement surveys',
    metricType: 'percentage',
    startValue: 65,
    targetValue: 90,
    currentValue: 82,
    progress: 68,
    confidenceLevel: 8,
    status: 'on_track',
    weight: 0.5,
    sortOrder: 2,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-15'),
  },
  // KRs for Manager capabilities objective
  {
    id: 'kr-nat-4',
    objectiveId: 'obj-nat-2',
    ownerId: 'user-natalie',
    title: 'Train 100% of managers on feedback and coaching',
    metricType: 'percentage',
    startValue: 0,
    targetValue: 100,
    currentValue: 85,
    progress: 85,
    confidenceLevel: 9,
    status: 'on_track',
    weight: 1,
    sortOrder: 0,
    createdAt: new Date('2026-01-02'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'kr-nat-5',
    objectiveId: 'obj-nat-2',
    ownerId: 'user-natalie',
    title: 'Achieve 80% 1-on-1 completion rate across all teams',
    metricType: 'percentage',
    startValue: 45,
    targetValue: 80,
    currentValue: 72,
    progress: 77,
    confidenceLevel: 8,
    status: 'on_track',
    weight: 1,
    sortOrder: 1,
    createdAt: new Date('2026-01-02'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'kr-nat-6',
    objectiveId: 'obj-nat-2',
    ownerId: 'user-hr1',
    title: 'Manager effectiveness score of 4.0+ out of 5',
    metricType: 'number',
    startValue: 3.2,
    targetValue: 4.0,
    currentValue: 3.7,
    progress: 63,
    confidenceLevel: 7,
    status: 'on_track',
    weight: 0.5,
    sortOrder: 2,
    createdAt: new Date('2026-01-02'),
    updatedAt: new Date('2026-01-15'),
  },
  // KRs for Hiring objective
  {
    id: 'kr-nat-7',
    objectiveId: 'obj-nat-3',
    ownerId: 'user-hr2',
    title: 'Reduce average time-to-hire from 45 to 30 days',
    metricType: 'number',
    startValue: 45,
    targetValue: 30,
    currentValue: 38,
    unit: 'days',
    progress: 47,
    confidenceLevel: 6,
    status: 'at_risk',
    weight: 1,
    sortOrder: 0,
    createdAt: new Date('2026-01-03'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'kr-nat-8',
    objectiveId: 'obj-nat-3',
    ownerId: 'user-natalie',
    title: 'Achieve 4.5+ new hire onboarding satisfaction score',
    metricType: 'number',
    startValue: 3.8,
    targetValue: 4.5,
    currentValue: 4.2,
    progress: 57,
    confidenceLevel: 7,
    status: 'on_track',
    weight: 1,
    sortOrder: 1,
    createdAt: new Date('2026-01-03'),
    updatedAt: new Date('2026-01-15'),
  },
]

import type { WeeklyCheckin, CheckinResponse, Meeting, AgendaItem, ActionItem, HighFive, HighFiveReaction, OKRCheckin } from './types'

export const natalieWeeklyCheckins: WeeklyCheckin[] = [
  {
    id: 'checkin-nat-1',
    userId: 'user-natalie',
    weekStartDate: new Date('2026-01-08'),
    pulseRating: 4,
    pulseComment: 'Feeling energized after the manager training kickoff!',
    status: 'reviewed',
    managerFeedback: 'Great progress on the manager training program. Keep up the momentum!',
    createdAt: new Date('2026-01-12'),
    updatedAt: new Date('2026-01-13'),
  },
  {
    id: 'checkin-nat-2',
    userId: 'user-natalie',
    weekStartDate: new Date('2026-01-15'),
    pulseRating: 3,
    pulseComment: 'Turnover numbers are concerning. Working on retention initiatives.',
    status: 'submitted',
    createdAt: new Date('2026-01-19'),
    updatedAt: new Date('2026-01-19'),
  },
]

export const natalieCheckinResponses: CheckinResponse[] = [
  {
    id: 'resp-nat-1',
    checkinId: 'checkin-nat-1',
    questionId: 'q-1',
    response: 'Successfully launched the manager coaching program with 25 managers in the first cohort. The feedback has been overwhelmingly positive!',
    createdAt: new Date('2026-01-12'),
  },
  {
    id: 'resp-nat-2',
    checkinId: 'checkin-nat-1',
    questionId: 'q-3',
    response: 'Focus on rolling out the engagement survey and analyzing results. Also preparing for the Q1 all-hands presentation on culture initiatives.',
    createdAt: new Date('2026-01-12'),
  },
  {
    id: 'resp-nat-3',
    checkinId: 'checkin-nat-2',
    questionId: 'q-2',
    response: 'We lost two key engineers this week. Need to do stay interviews with at-risk employees and accelerate our retention bonus program.',
    createdAt: new Date('2026-01-19'),
  },
]

export const natalieMeetings: Meeting[] = [
  {
    id: 'meeting-nat-1',
    hostId: 'user-natalie',
    participantId: 'user-hr1',
    title: '1-on-1 with Marcus',
    scheduledAt: new Date('2026-01-22T14:00:00'),
    duration: 30,
    status: 'scheduled',
    sharedNotes: 'Discuss engagement survey rollout and HRBP priorities for Q1',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'meeting-nat-2',
    hostId: 'user-natalie',
    participantId: 'user-hr2',
    title: '1-on-1 with Sophie',
    scheduledAt: new Date('2026-01-23T10:00:00'),
    duration: 30,
    status: 'scheduled',
    sharedNotes: 'Review recruiting pipeline and time-to-hire improvements',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'meeting-nat-3',
    hostId: 'user-1',
    participantId: 'user-natalie',
    title: '1-on-1 with Sarah (CEO)',
    scheduledAt: new Date('2026-01-24T09:00:00'),
    duration: 45,
    status: 'scheduled',
    sharedNotes: 'Quarterly people strategy review and budget discussion',
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-01-10'),
  },
]

export const natalieAgendaItems: AgendaItem[] = [
  {
    id: 'agenda-nat-1',
    meetingId: 'meeting-nat-1',
    title: 'Engagement survey timeline',
    description: 'Review launch date and communication plan',
    addedById: 'user-natalie',
    sortOrder: 0,
    createdAt: new Date('2026-01-15'),
  },
  {
    id: 'agenda-nat-2',
    meetingId: 'meeting-nat-1',
    title: 'HRBP coverage model',
    description: 'Discuss department assignments and workload',
    addedById: 'user-hr1',
    sortOrder: 1,
    createdAt: new Date('2026-01-16'),
  },
  {
    id: 'agenda-nat-3',
    meetingId: 'meeting-nat-2',
    title: 'Recruiting pipeline review',
    keyResultId: 'kr-nat-7',
    addedById: 'user-natalie',
    sortOrder: 0,
    createdAt: new Date('2026-01-15'),
  },
]

export const natalieActionItems: ActionItem[] = [
  {
    id: 'action-nat-1',
    meetingId: 'meeting-nat-1',
    title: 'Draft engagement survey questions',
    assigneeId: 'user-hr1',
    dueDate: new Date('2026-01-25'),
    status: 'pending',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
  },
  {
    id: 'action-nat-2',
    meetingId: 'meeting-nat-2',
    title: 'Analyze bottlenecks in interview scheduling',
    assigneeId: 'user-hr2',
    dueDate: new Date('2026-01-26'),
    status: 'pending',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
  },
]

export const natalieHighFives: HighFive[] = [
  {
    id: 'hf-nat-1',
    giverId: 'user-natalie',
    receiverId: 'user-hr1',
    message: 'Marcus, thank you for going above and beyond to support the engineering team through their recent reorg. Your empathy and professionalism made a real difference!',
    isPublic: true,
    valueIds: ['value-3', 'value-1'], // Teamwork, Customer First
    createdAt: new Date('2026-01-18'),
  },
  {
    id: 'hf-nat-2',
    giverId: 'user-1', // From CEO
    receiverId: 'user-natalie',
    message: 'Natalie, the manager training program launch was exceptional! The feedback from participants has been incredible. You\'re making a real impact on our culture.',
    isPublic: true,
    valueIds: ['value-2', 'value-5'], // Innovation, Growth Mindset
    createdAt: new Date('2026-01-16'),
  },
  {
    id: 'hf-nat-3',
    giverId: 'user-hr2',
    receiverId: 'user-natalie',
    message: 'Thank you for the mentorship and guidance on handling difficult candidate negotiations. I learned so much!',
    isPublic: true,
    valueIds: ['value-5'], // Growth Mindset
    createdAt: new Date('2026-01-14'),
  },
]

export const natalieHighFiveReactions: HighFiveReaction[] = [
  {
    id: 'reaction-nat-1',
    highFiveId: 'hf-nat-2',
    userId: 'user-natalie',
    emoji: '🙏',
    createdAt: new Date('2026-01-16'),
  },
  {
    id: 'reaction-nat-2',
    highFiveId: 'hf-nat-1',
    userId: 'user-hr1',
    emoji: '❤️',
    createdAt: new Date('2026-01-18'),
  },
]

export const natalieOKRCheckins: OKRCheckin[] = [
  {
    id: 'okr-checkin-nat-1',
    keyResultId: 'kr-nat-1',
    userId: 'user-natalie',
    previousValue: 42,
    newValue: 47,
    notes: 'Latest survey results show improvement. Team feedback sessions are helping.',
    wins: 'Engineering team NPS jumped 8 points after implementing new feedback loops',
    createdAt: new Date('2026-01-15'),
  },
  {
    id: 'okr-checkin-nat-2',
    keyResultId: 'kr-nat-4',
    userId: 'user-natalie',
    previousValue: 70,
    newValue: 85,
    notes: 'Completed second cohort of manager training. Only 3 more managers to go.',
    wins: 'Average training satisfaction score of 4.8/5',
    createdAt: new Date('2026-01-18'),
  },
  {
    id: 'okr-checkin-nat-3',
    keyResultId: 'kr-nat-2',
    userId: 'user-natalie',
    previousValue: 16,
    newValue: 14,
    notes: 'Small improvement but still concerning. Need to accelerate retention initiatives.',
    blockers: 'Competitor poaching in engineering. Need to review comp bands.',
    createdAt: new Date('2026-01-19'),
  },
]
